from __future__ import annotations


class RejectCode(str):
    # V1.0 — Hard validation
    INVALID_SYMBOL = "INVALID_SYMBOL"
    UNSUPPORTED_TIMEFRAME = "UNSUPPORTED_TIMEFRAME"
    INVALID_PRICE_STRUCTURE = "INVALID_PRICE_STRUCTURE"
    INVALID_NUMERIC_RANGE = "INVALID_NUMERIC_RANGE"
    INVALID_RR_PROFILE = "INVALID_RR_PROFILE"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"

    # V1.0 — Business rules
    DUPLICATE_SIGNAL = "DUPLICATE_SIGNAL"
    NEWS_BLOCKED = "NEWS_BLOCKED"
    COUNTER_TREND_HARD = "COUNTER_TREND_HARD"

    # V1.1 — SHORT_SQUEEZE hard rules
    SQ_NO_FIRED = "SQ_NO_FIRED"
    SQ_BAD_MOM_DIRECTION = "SQ_BAD_MOM_DIRECTION"
    SQ_BAD_VOL_REGIME = "SQ_BAD_VOL_REGIME"
    SQ_BAD_STRATEGY_NAME = "SQ_BAD_STRATEGY_NAME"

    # V1.1 — SHORT_SQUEEZE quality floors
    SQ_RSI_TOO_LOW = "SQ_RSI_TOO_LOW"
    SQ_KC_POSITION_TOO_HIGH = "SQ_KC_POSITION_TOO_HIGH"

    # V1.1 — SHORT_V73
    S_BASE_BAD_STRATEGY_NAME = "S_BASE_BAD_STRATEGY_NAME"
    S_BASE_RSI_TOO_LOW = "S_BASE_RSI_TOO_LOW"
    S_BASE_STOCH_TOO_LOW = "S_BASE_STOCH_TOO_LOW"

    # V1.1 — LONG_V73
    L_BASE_BAD_STRATEGY_NAME = "L_BASE_BAD_STRATEGY_NAME"
    L_BASE_RSI_TOO_HIGH = "L_BASE_RSI_TOO_HIGH"
    L_BASE_STOCH_TOO_HIGH = "L_BASE_STOCH_TOO_HIGH"

    # V1.1 — New rules
    RR_PROFILE_MISMATCH = "RR_PROFILE_MISMATCH"
    BACKEND_SCORE_TOO_LOW = "BACKEND_SCORE_TOO_LOW"

    # Fallback
    UNKNOWN = "UNKNOWN"


_RULE_TO_REJECT: dict[str, RejectCode] = {
    # V1.0 — Hard validation
    "SYMBOL_ALLOWED": RejectCode.INVALID_SYMBOL,
    "TIMEFRAME_ALLOWED": RejectCode.UNSUPPORTED_TIMEFRAME,
    "PRICE_VALID": RejectCode.INVALID_NUMERIC_RANGE,
    "DIRECTION_SANITY_VALID": RejectCode.INVALID_PRICE_STRUCTURE,
    "MIN_RR_REQUIRED": RejectCode.INVALID_RR_PROFILE,
    "CONFIDENCE_RANGE_VALID": RejectCode.LOW_CONFIDENCE,
    "MIN_CONFIDENCE_BY_TF": RejectCode.LOW_CONFIDENCE,
    # V1.0 — Business rules
    "DUPLICATE_SUPPRESSION": RejectCode.DUPLICATE_SIGNAL,
    "NEWS_BLOCK": RejectCode.NEWS_BLOCKED,
    "REGIME_HARD_BLOCK": RejectCode.COUNTER_TREND_HARD,
    # V1.1 — SHORT_SQUEEZE hard rules
    "SQ_NO_FIRED": RejectCode.SQ_NO_FIRED,
    "SQ_BAD_MOM_DIRECTION": RejectCode.SQ_BAD_MOM_DIRECTION,
    "SQ_BAD_VOL_REGIME": RejectCode.SQ_BAD_VOL_REGIME,
    "SQ_BAD_STRATEGY_NAME": RejectCode.SQ_BAD_STRATEGY_NAME,
    # V1.1 — SHORT_SQUEEZE quality floors
    "SQ_RSI_FLOOR": RejectCode.SQ_RSI_TOO_LOW,
    "SQ_KC_POSITION_FLOOR": RejectCode.SQ_KC_POSITION_TOO_HIGH,
    # V1.1 — SHORT_V73
    "S_BASE_BAD_STRATEGY_NAME": RejectCode.S_BASE_BAD_STRATEGY_NAME,
    "S_BASE_RSI_FLOOR": RejectCode.S_BASE_RSI_TOO_LOW,
    "S_BASE_STOCH_FLOOR": RejectCode.S_BASE_STOCH_TOO_LOW,
    # V1.1 — LONG_V73
    "L_BASE_BAD_STRATEGY_NAME": RejectCode.L_BASE_BAD_STRATEGY_NAME,
    "L_BASE_RSI_FLOOR": RejectCode.L_BASE_RSI_TOO_HIGH,
    "L_BASE_STOCH_FLOOR": RejectCode.L_BASE_STOCH_TOO_HIGH,
    # V1.1 — New rules
    "RR_PROFILE_MATCH": RejectCode.RR_PROFILE_MISMATCH,
    "BACKEND_SCORE_THRESHOLD": RejectCode.BACKEND_SCORE_TOO_LOW,
}


def rule_code_to_reject_code(rule_code: str) -> RejectCode:
    return _RULE_TO_REJECT.get(rule_code, RejectCode.UNKNOWN)
